services:
  db:
    image: postgres:16.0-alpine3.17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
    ports: [5432:5432]

  adminer:
    image: adminer
    restart: always
    ports: [8080:8080]

  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 15432:15432
    environment:
      - CUBEJS_DEV_MODE=true
    volumes:
      - .:/cube/conf